[package]
name = "easyversion"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bsdiff = "0.2.0"
bzip2 = "0.4.4"

[dev-dependencies]
divan = "0.1.14"

[[bench]]
name = "bench"
harness = false
