[package]
name = "easyversion"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bsdiff = "0.2.0"
bzip2 = "0.4.4"
dirs = "5.0.1"
ron = "0.8.1"
serde = {version = "1.0.215", features = ["derive"]}

[dev-dependencies]
divan = "0.1.15"
tempdir = "0.3.7"

[[bench]]
name = "bench"
harness = false
