[package]
name = "easyversion"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.19.0"
iced = "0.12.1"

[dev-dependencies]
divan = "0.1.14"

[[bench]]
name = "bench"
harness = false
